### ISSUE TITLE
5 remote assignment badge incorrectly awarded?

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#10]
pretty sure i only ticked the box for "remote" for Tigray. but am showing as having the badge for 5 remote assignments.
<img width="941" alt="Screen Shot 2023-03-16 at 2 33 38 PM" src="https://user-images.githubusercontent.com/4806884/225719795-69f7f6c4-6e71-4656-835f-aa3e7e49208f.png">

**Comment by JonathanGarro** [comment]
the cron that searches for people meeting specific badge criteria was not filtering for remote assignments. i actually think this was the original intent with this badge - i need to adjust the badge image language.

**Comment by JonathanGarro** [comment]
I've updated the code that handles these alerts. The SQL query had an error, but I've fixed it and updated it to SQLAlchemy to ensure it's cross-compatible between my local SQLite db and the production Postgres db.
