### ISSUE TITLE
Links to profiles broken (differently constructed URLs)

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#103]
On https://rcrcsims.org/resources if I click on a profile (e.g. Web Visualization or Geospatial) it takes me to a 404 on learn-sims.

e.g. https://rcrcsims.org/resources links to
https://learn-sims.org/docs/geospatial (which gives 404).  URL should have "resources" instead of "docs" - i.e. should link to https://learn-sims.org/category/geospatial/

Cheers!

**Comment by JonathanGarro** [comment]
yikes! thanks for the heads up. must have happened during the hosting transition.

**Comment by JonathanGarro** [comment]
this has been fixed, thanks @nanometrenat
