### ISSUE TITLE
Link updates please - to stable URLs of competency frameworks

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#105]
Hi there,

https://learn-sims.org/resources-and-standards/remote-profile-specializations-and-tiers/ has links to both the IM tech competency framework and the Core Competency framework.

- [ ] Currently the IM Tech CF links to a google doc draft version - may you please instead link to the stable URL of the final published version instead?  `https://go.ifrc.org/surge/catalogue/information-management#:~:text=Technical%20Competency%20Framework`
- [ ] Currently the Core CF links to a specific published version - may you please instead link to the stable URL instead?  `https://surgelearning.ifrc.org/resources/core-competency-framework-surge-personnel`

That means that SIMS Portal won't need to be updated each time the versions of these docs change.

Cheers!

**Comment by JonathanGarro** [comment]
updated.
