### ISSUE TITLE
Unicode error in Acronyms CSV export

### ISSUE THREAD

**Issue by ioalexei** [JonathanGarro/SIMS-Portal#106]
ALA acronym shows correctly as `Åland Islands` in the table on the website but shows as `Ã…land Islands` in the CSV export

From a quick scan also affects: BCG, BLM, CHAST, CIV - and probably some others

**Comment by JonathanGarro** [comment]
thanks @ioalexei i will dig into this

**Comment by ioalexei** [comment]
Update on this - with the new functionality from #107 the CSV download now has lots of extra text in the first column - e.g.  
```
Acronym (English)
----------------
AAP                                                                                                  Acronym Details                                                                                                                                English                         AAP                                                                                                                                                                                     Definition                         Accountability to Affected Populations                                                                                                                                                                                                                                                                                                                                                                                     Permalink                                                                                        Close
```

**Comment by ioalexei** [comment]
One more thought on this - at the moment the CSV downloads as `SIMS.csv`. Could it be something like `SIMS-acronyms.csv` ?

**Comment by JonathanGarro** [comment]
yikes, didn't notice the export mess. i'll dig into that as part of this issue

**Comment by JonathanGarro** [comment]
@ioalexei I've rebuilt the JS that loads that CSV and pushed it up to prod. Can you take a look and let me know if that solves the data export issue you saw? I also changed the default name of the generated file.

I still need to solve the encoding issue.

**Comment by ioalexei** [comment]
@JonathanGarro thanks - looks fixed now, and downloads with the new file name.
