### ISSUE TITLE
[Feature request] Acronyms - alternative view with more details on one screen

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#107]
Re the excellent new https://rcrcsims.org/acronyms

### Context
One of the things I liked about MTAG was the ability to scroll down and see all the details of the various acronyms without having to individually click into each one.

In discussion with @JonathanGarro and @ioalexei today we saw two use cases for people looking at the acronyms:

1. people coming to find the explanation for a specific acronym - here the existing page + filter/search process workds great
2. people coming to see what kind of information is held on the acronym buster - and therefore what kind of info they can expect to look up and find

This feature request is to cover use case 2

### Request
Please create an alternative view of the acronyms - perhaps more compact (smaller text and a bit more dense) where you don't have to click in to each item to see the definition.

Thanks

**Comment by JonathanGarro** [comment]
Here's my proposed view switcher:

![Screen Shot 2024-02-26 at 11 07 46 AM](https://github.com/JonathanGarro/SIMS-Portal/assets/8890661/02248d6c-a3c7-40bc-8324-9e85c36eb7b5)

@nanometrenat lmk what you think.

**Comment by JonathanGarro** [comment]
![2024-02-28 08 46 45](https://github.com/JonathanGarro/SIMS-Portal/assets/8890661/e5f7af46-9ed8-410c-ae8b-4eb4fc6ba67d)

@nanometrenat i've added two view enhancements to https://rcrcsims.org/acronyms - 

1. when viewing the regular view, clicking on an acronym link (far left column) brings ups a modal with additional info (see gif above)
2. the compact view is now more compact
