### ISSUE TITLE
[Feature request] Allowing contributions to the acronyms from both public and logged-in users

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#108]
Re the excellent new https://rcrcsims.org/acronyms

### Context
Current MTAG system (from which this was migrated) allows public contributions - which is great for crowdsourcing but also potentially allows incorrect or malicious contributions to go live.  Want to balance up appropriate level of scrutiny with frictionless contribution experience.

### Request
Please allow logged-in SIMS Portal users to contribute directly, no gatekeeping, but with monitoring alerts so admins know a contribution has been made and can check it (action only required if it's not good quality)

Please allow public to make contributions that are held in a queue (gatekept) until an admin approves them for publication

**Comment by JonathanGarro** [comment]
@nanometrenat  lmk if this routing makes sense to you

**Comment by nanometrenat** [comment]
Question - what is the _update_ process?  e.g. for adding additional languages, or amending a definition, or adding a URL?

**Comment by JonathanGarro** [comment]
@nanometrenat I added an edit route. when looking at the acronym popup, it will check if the user is an administrator OR the person that originally submitted the acronym (login required in order to run the check, otherwise no edit button appears). it will then bring up the same page as the submission, except with the data already populated.

**Comment by JonathanGarro** [comment]
Closing this issue. Current implementation: 

- Logged in users can add new acronyms and have them appear instantly. Their account ID is associated so we have a clear audit trail.
- Public users must enter a name and email address to associate with the acronym, pass a reCAPTCHA check, and then their submission is placed into a queue to be approved by a site admin. We'll need to add some guidance documentation for what they should be looking for (e.g. is this a duplicate? is this accurate? is this relevant? etc.)
- There are two ways to edit acronyms: users that submitted it can click on the acronym from the table, and they will see an Edit button if they created it. Admins can also edit any acronym.
