### ISSUE TITLE
profile image disappeared

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#11]
i had uploaded a profile image, and the URL is showing as `https://d3s70q3c7pqvju.cloudfront.net/static/assets/img/avatars/1a4f0396aeb2ed85.jpg` (instead of the `default.jpg`) but it's not loading

<img width="331" alt="Screen Shot 2023-03-16 at 2 37 36 PM" src="https://user-images.githubusercontent.com/4806884/225720455-60ac9467-a189-4db4-b663-7a5599b0bb73.png">

**Comment by JonathanGarro** [comment]
This has been resolved with a fix for where the files are being stored. They are now stored with an images folder in S3.
