### ISSUE TITLE
Portal Github issues list has wrong assignee 

### ISSUE THREAD

**Issue by ioalexei** [JonathanGarro/SIMS-Portal#122]
The top issue in the GitHub issues list for Hurricane Beryl shows it's assigned to a user: https://rcrcsims.org/emergency/81

But the issue and card on the GitHub repo/board are unassigned: https://github.com/orgs/Surge-Information-Management-Support/projects/11/views/1?pane=issue&itemId=70647675

**Comment by JonathanGarro** [comment]
thanks for flagging. looks like the wrong type of join in sqlalchemy is causing this. will look into

**Comment by JonathanGarro** [comment]
ive implemented a proposed fix in 1.12.1 - ive confirmed it works on the brazil response, but @ioalexei if the repo is still syncing with the portal after marking it as private, lmk if the issue you flagged with beryl has been fixed

**Comment by JonathanGarro** [comment]
scratch that, error persists. will ping when i have another solution

**Comment by JonathanGarro** [comment]
ok i think ive fixed this. if you dont see the data you're expecting, try using the refresh button. if problem persists, we can reopen this issue.

**Comment by ioalexei** [comment]
Looking good for me now - thanks!
