### ISSUE TITLE
500 error when submitting a new acronym

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#126]
Hi there,

Tried to submit a new acronym for the first time via the portal - got a 500 error, not sure if this is because I used the new fields introduced via https://github.com/JonathanGarro/SIMS-Portal/issues/124 ?  SORRY!

![image](https://github.com/user-attachments/assets/bcea8a81-db5b-4140-abc7-05322dbf722e)

I am logged in, and this is what I was trying to submit:

![image](https://github.com/user-attachments/assets/a8ce5e76-2b2b-4597-ae45-c9b8e4ba4981)

Acronym (English): PPP
Definition (English): Pilot Programmatic Partnership
Explanation (English): Now called the Programmatic Partnership (originally a Pilot), this is a partnership between the IFRC, many of our member National Societies, and the European Union.
Category = Red Cross Red Crescent
Relevant country (if applicable) = blank
URL = https://www.ifrc.org/get-involved/partner-us/multilaterals-and-international-financial-institutions/programmatic

**Comment by nanometrenat** [comment]
JG has already fixed this, just successfully submitted the above new acronym - thanks!

**Comment by JonathanGarro** [comment]
fixed in [1.12.3](https://github.com/JonathanGarro/SIMS-Portal/blob/main/CHANGELOG.md#1123-dupont-circle---2024-07-31)
