### ISSUE TITLE
About page: Most recent SIMS activation disaster not populating

### ISSUE THREAD

**Issue by katherinelilly** [JonathanGarro/SIMS-Portal#13]
<img width="387" alt="Screen Shot 2023-03-17 at 1 55 19 PM" src="https://user-images.githubusercontent.com/80766759/225982146-273e905d-f583-40f8-ba0f-1cb4622a7943.png">

"SIMS has been activated 58 times since its inception in 2013, most recently in response to the Testasdf." - the name of the most recent activation isn't populating.

**Comment by JonathanGarro** [comment]
thanks Katie - this pulls based on the "date created" field on the emergency. i did this assuming emergencies would get added in sequential order as we respond to them. but if there are cases where we create an emergency that we missed in the database, we'll just need to manually edit that field to prevent it from showing up as the latest. this can be done via **Admin Portal > Admin Backend > Emergencies**
