### ISSUE TITLE
Tigray emergency link broken

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#15]
<img width="879" alt="Screen Shot 2023-03-20 at 9 25 30 AM" src="https://user-images.githubusercontent.com/4806884/226353662-e30ae0de-a6a3-41e2-9a51-f7cf685e1131.png">

the link is this: https://d3s70q3c7pqvju.cloudfront.net/emergency/62

```
TypeError
TypeError: object of type 'NoneType' has no len()
```

<img width="1518" alt="Screen Shot 2023-03-20 at 9 25 18 AM" src="https://user-images.githubusercontent.com/4806884/226353475-1d62d56b-f3e5-4c4a-a985-23f06046e6fd.png">

**Comment by JonathanGarro** [comment]
thanks dan. this was related to a line in the Python that was looking for the length of characters in the Activation Details field, which wasn't filled in. I thought I'd toggled data-required as True for this route, but I guess I missed it. This should be resolved by now requiring data there when creating a new emergency record, and the Tigray link should now be functional.
