### ISSUE TITLE
Profile photo upload challenge

### ISSUE THREAD

**Issue by katherinelilly** [JonathanGarro/SIMS-Portal#16]
I can't seem to upload a profile photo. I attach the image and click Save Profile, but nothing happens. But I see that Dan was able to upload his photo so I'm not sure why it isn't working for me.

**Comment by JonathanGarro** [comment]
@katherinelilly can you post the image here, along with the file format type and dimensions?

**Comment by katherinelilly** [comment]
JPEG, 2316 × 3088 (880 KB)
![profile photo ifrc](https://user-images.githubusercontent.com/80766759/226391427-328fee03-3137-46d3-a04b-edcecd3f7b14.jpeg)

**Comment by katherinelilly** [comment]
Yes, it worked with a <1000px image! Sorry!

**Comment by JonathanGarro** [comment]
No, that was good to catch, I need to add that as guidance on the page.
