### ISSUE TITLE
Nice to have: specify product file size limits when uploading

### ISSUE THREAD

**Issue by katherinelilly** [JonathanGarro/SIMS-Portal#17]
I tried to upload a zipped file containing some QGIS files and it was understandable too large (~52MB). As predicted it didn't upload and gave an error message, but maybe specify in the descriptive text what the file size limit is.

**Comment by JonathanGarro** [comment]
thanks @katherinelilly - do you recall what generic language the error message gave you? Did it say something like "There was an error posting your product. Please make sure you have filled out all required fields and selected a compatible file." or was it a non-native error screen with a lot of info about the traceback?

**Comment by katherinelilly** [comment]
<img width="282" alt="Screen Shot 2023-03-20 at 3 34 40 PM" src="https://user-images.githubusercontent.com/80766759/226447211-3da7ec90-eeb7-4329-87f5-2e3d8db992b8.png">
Here is the error. Thanks, Jonathan!

**Comment by JonathanGarro** [comment]
great, thanks - as a specific error this helps with exception handling. i have error 413s caught with a new error page:

![2023-03-20 16 10 12](https://user-images.githubusercontent.com/8890661/226454449-893260d6-73a4-4cb3-bce0-e24a98e9cdd8.gif)
