### ISSUE TITLE
date formatting in info box for gantt chart

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#39]
formatting of the dates in the info box for the gantt view not happening
<img width="930" alt="Screen Shot 2023-06-06 at 3 07 51 PM" src="https://github.com/JonathanGarro/SIMS-Portal/assets/4806884/abe8289f-009c-4044-9ffe-b39c31300e06">

**Comment by JonathanGarro** [comment]
Closing this as we have moved availability (which has the date values) into a separate table.
