### ISSUE TITLE
availability checkboxes don't reflect values on subsequent edits

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#40]
updated my availability once, went back to update it again and all the boxes started checked again (ignoring the previous values)

<img width="761" alt="Screen Shot 2023-06-06 at 3 18 48 PM" src="https://github.com/JonathanGarro/SIMS-Portal/assets/4806884/ef821b6a-643c-4177-9477-03e58a1678ee">

<img width="526" alt="Screen Shot 2023-06-06 at 3 18 54 PM" src="https://github.com/JonathanGarro/SIMS-Portal/assets/4806884/3cb068dc-0082-42d6-bf8b-d2919c7716b3">

**Comment by JonathanGarro** [comment]
Same as #41 - this is no longer relevant given changes to availability reporting changes.
