### ISSUE TITLE
"Days Left" white font on white background when early in assignment

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#42]
<img width="198" alt="Screen Shot 2023-06-06 at 3 21 30 PM" src="https://github.com/JonathanGarro/SIMS-Portal/assets/4806884/f66ec4b1-a36d-4c03-bbc7-5474540374f9">

**Comment by JonathanGarro** [comment]
We have removed start and end dates from assignments, so this has been OBE.
