### ISSUE TITLE
"Template not found" error page when clicking through from support profiles

### ISSUE THREAD

**Issue by pknight03** [JonathanGarro/SIMS-Portal#52]
On my personal profile page, I clicked "see tiers" on the "support profiles" section on the left of the page (https://rcrcsims.org/profile/view/24), then if I click the badge provided (https://rcrcsims.org/support_profiles/24), it takes me here (https://rcrcsims.org/role_profile/Geo) which displays "Template not found". 

This is the same for other people's pages too

![image](https://github.com/JonathanGarro/SIMS-Portal/assets/8642071/5ee354e5-d36c-499f-9873-cf0a0b237fef)

**Comment by JonathanGarro** [comment]
The link constructor was inheriting a name in capital case. I've added `|lower` to the jinja tag, which seems to have solved this. Will be included in next release.
