### ISSUE TITLE
French translation of the map disclaimer for the "Map Disclaimers" page on learn-sims.org

### ISSUE THREAD

**Issue by pknight03** [JonathanGarro/SIMS-Portal#78]
This page: https://learn-sims.org/docs/style-guidance/disclaimer-text-295/ does not have a French translation of the map disclaimer. 

Here: https://trello.com/c/i2HXBJGY/1-map-disclaimers is the disclaimer used for Haiti 2021. 
"Les cartes ci-utilisées ne sont en aucune façon l'expression des positions de la Fédération Internationale des Sociétés de la Croix-Rouge et du Croissant-Rouge ou des Sociétés Nationales quant au statut juridique d'un territoire ou de ses autorités.

Les cartes sont produites par SIMS."

_I dont speak French so cant verify if it is correct or not!_

**Comment by JonathanGarro** [comment]
Thanks @pknight03 - I've updated the page.
