### ISSUE TITLE
error when saving work location - Google API error

### ISSUE THREAD

**Issue by nanometrenat** [JonathanGarro/SIMS-Portal#86]
Am logged in to the portal as a member.
Went to my profile, clicked Save Work Location, input my address city/country - however https://rcrcsims.org/save_work_location/44 returns an error:
`Google Maps Platform rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxx, with referer: https://rcrcsims.org/save_work_location/44`
![image](https://github.com/JonathanGarro/SIMS-Portal/assets/33625192/b933162c-244f-463c-b358-2d7c50887969)

**Comment by nanometrenat** [comment]
Seems to have saved OK anyway, even though it gave me the above error onscreen.  Thanks!

**Comment by JonathanGarro** [comment]
thanks @nanometrenat - looks like the API key's application restriction setting changed on its own somehow. i think i resolved this, let me know if it works now for you.
