### ISSUE TITLE
Upgrade profile edit form for skills and languages

### ISSUE THREAD

**Issue by JonathanGarro** [JonathanGarro/SIMS-Portal#89]
The command/control key for multiple options is clunky. Lets upgrade this to checkboxes/buttons.

**Comment by MarijePlak** [comment]
Hi Jonathan, it would also be great if users could rank their skills, as I think they are currently listed randomly on my profile. For example: I chose Dutch, English, French, Spanish and German as my languages. It currently lists French and Spanish before Dutch and English I think, whereas my actual skills in Dutch and English are better than French and Spanish. Same goes for the skills listed above that (currently seems listed randomly, but I feel more confident in Power BI, QGIS and Kobo than in Tableau, even though I'm able to use Tableau etc). Is there a way we can rank our skills ourselves? For example by being able to click stars out of 5 or rank out of 10 on how confident we feel in a certain skill or language?

**Comment by JonathanGarro** [comment]
I've upgraded the skill and language picker as part of 1.7.2. 

@MarijePlak - I'm moving your feedback to a separate card in my dev roadmap. Having folks provide that level of detail was something we'd considered, but ultimately tabled the idea after conversations about the point of the skill and language reporting on your profile. The discussion revolved around the underlying purpose of the feature, which we decided was to simply broadcast to the network that you can be a resource for questions about skill X or that they can come to you if they need support in language Y. While having more granular control over those would offer richer data, it would also require more user curation of their data at a degree to which we have yet to see people willing to do. However, it is a good idea, and one that we'll consider again in a future dev cycle.
