### ISSUE TITLE
error on creating emergency

### ISSUE THREAD

**Issue by danbjoseph** [JonathanGarro/SIMS-Portal#9]
throws an error
<img width="1667" alt="Screen Shot 2023-03-16 at 12 04 28 PM" src="https://user-images.githubusercontent.com/4806884/225680788-b95339b4-337e-4179-bcf4-5a906b4f5c31.png">
but the new emergency does show up
<img width="1387" alt="Screen Shot 2023-03-16 at 12 05 15 PM" src="https://user-images.githubusercontent.com/4806884/225680926-066920e9-0c59-441c-91a7-67752c7e87f5.png">

**Comment by JonathanGarro** [comment]
thanks - this is related to [issue 7](https://github.com/JonathanGarro/SIMS-Portal/issues/7) and a csv file that gets updated on creation, but the directory isn't there. this should be fixed with that directory solution.

**Comment by JonathanGarro** [comment]
fixed and deployed. issue was missing csv file that gets updated with active emergencies. ive moved the filepath in the EFS structure on AWS to include this file.
