### ISSUE TITLE
Add border to images on portfolio pages

### ISSUE THREAD

**Issue by ioalexei** [JonathanGarro/SIMS-Portal#91]
Since most print products will have a white background, is it possible to add a thin border or subtle drop shadow to help it stand out against the white page background?

E.g. on [this portfolio page](https://rcrcsims.org/portfolio/view/25 ) it's hard to see where the edges of the map end and the page background starts

**Comment by JonathanGarro** [comment]
Processed, added to upcoming 1.6.1 release.
