### ISSUE TITLE
Edit text of submit button on availability page

### ISSUE THREAD

**Issue by ioalexei** [JonathanGarro/SIMS-Portal#99]
On the page where you can submit your availability for the coming week, the submit button has the text "Submit Query" - 
perhaps just "Submit" or "Save" would be better, as the "query" part might be confuding

![image](https://github.com/JonathanGarro/SIMS-Portal/assets/3179403/9de603b4-c8cd-44ac-96fa-b2c9ff7ca3e3)

**Comment by JonathanGarro** [comment]
Fixed and added to the upcoming 1.7.6 release. Thanks @ioalexei
